// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vskilcfwuvllykeelgfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZza2lsY2Z3dXZsbHlrZWVsZ2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjY5MzgsImV4cCI6MjA3MjgwMjkzOH0.iOmlezSibbjbMcsxj9WMOrTEA59Wq0tbzQY1fs_X5YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});